---

all:
  children:
    mongo_servers:
      children:
        mongo_shard_servers:  # mongod database shard servers
          vars:
            mongod_secret_key: "{{ lookup('file', inventory_dir ~ '/secrets/rsd0') }}"
          hosts:
            192.168.53.101:
            192.168.53.102:
            192.168.53.103:
        mongo_config_servers:  # mongod config servers
          vars:
            mongoc_secret_key: "{{ lookup('file', inventory_dir ~ '/secrets/rsc0') }}"
          hosts:
            192.168.53.101:
            192.168.53.102:
            192.168.53.103:
        mongo_query_servers:  # mongos query servers
          hosts:
            192.168.53.104:

